# /setup/roles/common/tasks/main.yml
#
# ansible playbook file
#
# configures hosts for Cabrillo ROV 2023
# sub-playbook for common configuration
#
# Copyright (C) 2022-2023 Cabrillo Robotics Club
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Cabrillo Robotics Club
# 6500 Soquel Drive Aptos, CA 95003
# cabrillorobotics@gmail.com
#
---

- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: ansible-common
  register: tempdir_common

- name: Copy files to remote
  ansible.builtin.copy:
    src: files/
    dest: {{ tempdir_common.path }}
  when: tempdir_common.path is defined

- name: Installing extra packages needed by Seahawk
  ansible.builtin.apt:
    name:
      - libavdevice-dev 
      - libavformat-dev 
      - libavcodec-dev 
      - libavutil-dev 
      - libswscale-dev
      - ros-humble-v4l2-camera
      - ros-humble-image-transport-plugins
      - v4l-utils
      - python3-pip
      - ros-iron-tf2
      - ros-iron-tf2-py
      - ros-iron-tf2-ros
      - ros-iron-tf2-ros-py
    state: present

- name: Installing Python packages in your home directory with PIP
  become: false
  ansible.builtin.pip:
    requirements: "{{ tempdir_common.path }}/requirements.txt"

- name: Cleanup temporary directory
  ansible.builtin.file:
    path: {{ tempdir_common.path }}
    state: absent
  when: tempdir_common.path is defined
